### ISSUE TITLE
Remove dev dependencies from npm package

### ISSUE THREAD

**Issue by andreujuanc** [celo-org/bls12377js#14]
Hi, 

I'm using a library (https://github.com/BitGo/BitGoJS/issues/956) which uses a library that uses this package 😄 

There are several problems: 
**Problem #1:** you are including `typescript` and `@types` in the npm package. 
- Solution: Can you please do `npm prune --production` before hand?

Problem #2: dev dependencies on incorrect location in package.json
- Solution:
```diff
  "dependencies": {
-   "@types/node": "^12.11.7",
    "big-integer": "^1.6.44",
    "@stablelib/blake2xs": "0.10.4",
-  "chai": "^4.2.0",
-  "mocha": "^6.2.2",
-  "ts-node": "^8.4.1",
-  "typescript": "^3.6.4"
  },
  "devDependencies": {
+  "@types/node": "^12.11.7",
+  "chai": "^4.2.0",
+  "mocha": "^6.2.2",
+  "ts-node": "^8.4.1",
+  "typescript": "^3.6.4",
    "@types/chai": "^4.1.7",
    "@types/mocha": "^5.2.7"
  }
```

If you do this, I will get a 50MB size decrease in my deployment!! <3

Thank you

**Comment by carterqw2** [comment]
Done in #15.

**Comment by andreujuanc** [comment]
Thanks @carterqw2  🎉
